ci test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,11 +82,150 @@ jobs:
           submodules: true
           token: ${{ secrets.PAT_REVIEW }}
 
+      - name: Use cassettes previously sent
+        if: ${{ github.event_name == 'pull_request_target' }}
+        run: |
+          new_branch="${{ github.event.pull_request.user.login }}-${{ github.event.pull_request.head.ref }}"
+          git config --global user.name "Github Actions"
+          git config --global user.email "github-actions@github.com"
+          cd tests/Auto-GPT-test-cassettes
+
+          if git ls-remote --exit-code --heads origin $new_branch ; then
+            git fetch origin $new_branch:$new_branch
+            git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
+
+            git checkout $new_branch
+
+            if git merge --no-commit --no-ff ${{ github.event.pull_request.base.ref }}; then
+              echo "No merge conflict detected. We can use the cassettes previously sent."
+            else
+              echo "Merge conflict detected. This means we cannot use the cassettes previously sent, so we will take the cassettes of ${{ github.event.pull_request.base.ref }}."
+              git merge --abort
+              git checkout ${{ github.event.pull_request.base.ref }}
+            fi
+          else
+            echo "Branch $new_branch does not exist. We will use the cassettes of ${{ github.event.pull_request.base.ref }}"
+          fi
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Run pytest tests with coverage
+        run: |
+          pytest tests/integration/challenges/basic_abilities/test_write_file.py
+          python tests/integration/challenges/utils/build_current_score.py
+        env:
+          CI: true
+          PROXY: ${{ secrets.PROXY }}
+          AGENT_MODE: ${{ vars.AGENT_MODE }}
+          AGENT_TYPE: ${{ vars.AGENT_TYPE }}
+
+      - name: Update cassette submodule to push target if push event
+        if: ${{ github.event_name == 'push' }}
+        run: |
+          current_branch=$(echo ${{ github.ref }} | sed -e "s/refs\/heads\///g")
+          git config --global user.name "Auto-GPT-Bot"
+          git config --global user.email "github-bot@agpt.co"
+
+          if ! git diff --quiet -- tests/integration/challenges/current_score.json; then
+            git add tests/integration/challenges/current_score.json
+            git commit -m "Update current score"
+            git push origin HEAD:refs/heads/$current_branch
+          else
+            echo "The current score didn't change."
+          fi
+
+          cd tests/Auto-GPT-test-cassettes
+          git fetch origin $current_branch
+
+          # Check if there are any changes
+          if ! git diff --quiet; then
+            git add .
+            git commit -m "Auto-update cassettes after Push event"
+            git pull --rebase origin $current_branch
+
+            git push origin HEAD:refs/heads/$current_branch
+
+            cd ../..
+            git add tests/Auto-GPT-test-cassettes
+            git commit -m "Update submodule reference"
+            git push origin HEAD:refs/heads/$current_branch
+          else
+            echo "No cassettes changes to commit"
+          fi
+
+      - name: Update cassette submodule to submodule branch if PR event
+        if: ${{ github.event_name == 'pull_request_target' }}
+        run: |
+          new_branch="${{ github.event.pull_request.user.login }}-${{ github.event.pull_request.head.ref }}"
+
+          cd tests/Auto-GPT-test-cassettes
+          git config --global user.name "Auto-GPT-Bot"
+          git config --global user.email "github-bot@agpt.co"
+
+          # Check if there are any changes
+          if ! git diff --quiet; then
+            git add .
+            git commit -m "Auto-update cassettes after merging PR #${{ github.event.pull_request.number }}"
+            git push -f origin HEAD:refs/heads/$new_branch    
+          else
+            echo "No changes to commit"
+            exit 0
+          fi
+          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }} || echo "DIFF_EXISTS=false" >> $GITHUB_ENV
+          differences=$(git diff origin/$new_branch origin/${{ github.event.pull_request.base.ref }})
+
+          if [ -n "$differences" ]; then
+            echo "DIFF_EXISTS=true" >> $GITHUB_ENV
+          else
+            echo "DIFF_EXISTS=false" >> $GITHUB_ENV
+          fi
+
+      - name: Beat Challenges
+        if: ${{ env.DIFF_EXISTS == 'true' }}
+        run: |
+          pytest -n auto tests/integration/challenges/memory/test_memory_challenge_c.py tests/integration/challenges/basic_abilities/test_write_file.py --beat-challenges --cov=autogpt --cov-report term-missing --cov-branch --cov-report xml --cov-report term
+          python tests/integration/challenges/utils/build_current_score.py
+        env:
+          CI: true
+          PROXY: ${{ secrets.PROXY }}
+          AGENT_MODE: ${{ vars.AGENT_MODE }}
+          AGENT_TYPE: ${{ vars.AGENT_TYPE }}
+
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v3
+
+      - name: Beat challenges - Update cassette submodule to submodule branch if PR event
+        if: ${{ env.DIFF_EXISTS == 'true' }}
+        run: |
+          new_branch="${{ github.event.pull_request.user.login }}-${{ github.event.pull_request.head.ref }}"
+
+          cd tests/Auto-GPT-test-cassettes
+          git config --global user.name "Auto-GPT-Bot"
+          git config --global user.email "github-bot@agpt.co"
+
+          # Check if there are any changes
+          if ! git diff --quiet; then
+            git add .
+            git commit -m "Auto-update cassettes after merging PR #${{ github.event.pull_request.number }} (Beat challenges)"
+            git push -f origin HEAD:refs/heads/$new_branch
+          else
+            echo "No changes to commit"
+            exit 0
+          fi
+
       - name: Create Pull Request
         run: |
           current_date_time=$(date +'%Y%m%d%H%M%S')
           new_branch="update-score-${{ github.event.pull_request.number }}-$current_date_time"
-          
+
           git config --global user.name "Auto-GPT-Bot"
           git config --global user.email "github-bot@agpt.co"
           echo "test" >> tests/integration/challenges/current_score.json
@@ -94,11 +233,11 @@ jobs:
             git add tests/integration/challenges/current_score.json
             git commit -m "Update score"
             git checkout -b $new_branch
-          
+
             echo ${{ secrets.PAT_REVIEW }} | gh auth login --with-token
-          
+
             git remote add base https://github.com/${{ github.event.pull_request.base.repo.full_name }}.git
-          
+
             git push base $new_branch
             echo "Base branch: ${{ github.event.pull_request.head.ref }}"
 
@@ -109,4 +248,29 @@ jobs:
             --repo ${{ github.event.pull_request.head.repo.full_name }}
           else
             echo "The current score didn't change."
+          fi
+      
+
+      - name: Apply or remove behaviour change label and comment
+        if: ${{ github.event_name == 'pull_request_target' }}
+        run: |
+          TOKEN=${{ secrets.PAT_REVIEW }}
+          REPO=${{ github.repository }}
+
+          if [[ "${{ env.DIFF_EXISTS }}" == "true" ]]; then
+            echo "Adding label and comment..."
+            curl -X POST \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO/issues/${{ github.event.pull_request.number }}/labels \
+            -d '{"labels":["behaviour change"]}'
+
+            echo $TOKEN | gh auth login --with-token
+            gh api repos/$REPO/issues/${{ github.event.pull_request.number }}/comments -X POST -F body="You changed AutoGPT's behaviour. The cassettes have been updated and will be merged to the submodule when this Pull Request gets merged."
+          else
+            echo "Removing label..."
+            curl -X DELETE \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$REPO/issues/${{ github.event.pull_request.number }}/labels/behaviour%20change
           fi
